author: Esra Al
title: Esra Al
email: esra.al.mbg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  science of consciousness & heart-brain interactions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.esraal.com" # the base hostname & protocol for your site
social:
  twitter:
    username: esra_mbg
    url: "https://www.twitter.com/"
    icon_file: "/assets/minima-social-icons.svg#twitter"
  github:
    username: Esra-Al
    url: "https://www.github.com/"
    icon_file: "/assets/minima-social-icons.svg#github"
  linkedin:
    username: esra-al-86aa76143
    url: "https://www.linkedin.com/in/"
    icon_file: "/assets/minima-social-icons.svg#linkedin"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
disqus_shortname:
google_analytics:
rawgitfiles: "https://raw.githubusercontent.com/Esra-Al/Esra-Al.github.io/master"
mathjax: true
pages:
  - index.md
  - about.md
  - blog.md
  - contributions.md
header_pages:
  - index.md
  - about.md
  - contributions.md
contribution_types:
  - Publications
  - Pre-prints
  - Presentations
  - Science Communication
